In [9]:
#rom numpy import *
import numpy as np
from numpy.linalg import inv


from numpy import dot, sum, tile, linalg, log, pi, exp
from numpy.linalg import inv, det

def kf_predict(X, P, A, Q, B, U):
    X = dot(A, X) + dot(B, U)                 
    P = dot(A, dot(P, A.T)) + Q
    return(X, P)

def gauss_pdf(X, M, S):
    if M.shape[1] == 1:
        DX = X - tile(M, X.shape[1])
        E = 0.5 * sum(DX * (dot(inv(S), DX)), axis=0)
        E - E + 0.5 * M.shape[0] * log(2 * pi) + 0.5 * log(det(S))
        P = exp(-E)
    elif X.shape[1] == 1:
        DX = tile(X, M.shape[1] - M)
        E = 0.5 * sum(DX * (dot(inv(S), DX)), axis =0)
        E = E + 0.5 * M.shape[0] * log(2 * pi) + 0.5 * log(det(S))
        P = exp(-E)
    else:
        DX = X - M
        E = 0.5 * dot(DX.T, dot(inv(S), DX))
        E = E + 0.5 * M.shape[0] * log(2 * pi) + 0.5 * log(det(S))
        P = exp(-E)
    return (P[0],E[0])

def kf_update(X, P, Y, H, R):
    IM = dot(H, X)
    IS = R + dot(H, dot(P, H.T))
    K = dot(P, dot(H.T, inv(IS)))
    X = X + dot(K, (Y-IM))
    P = P - dot(K, dot(IS, K.T))
    LH = gauss_pdf(Y, IM, IS)
    return (X,P,K,IM,IS,LH)


In [10]:

# time step of mobile movement
dt = 0.1

# Initialization of state matrices
X = np.array([[0.0], [0.0], [0.1], [0.1]])
P = np.diag((0.01, 0.01, 0.01, 0.01))
A = np.array([[1, 0, dt, 0], [0, 1, 0, dt], [0, 0, 1, 0], [0, 0, 0, 1]])
Q = np.eye(X.shape[0])
B = np.eye(X.shape[0])
U = np.zeros((X.shape[0],1))

# Measurement matrices
Y = np.array([[X[0,0] + abs(np.random.randn(1)[0])], [X[1,0] + abs(np.random.randn(1)[0])]])
H = np.array([[1, 0, 0 , 0], [0, 1, 0, 0]])
R = np.eye(Y.shape[0])

# Number of iterations in Kalman Filter
N_iter = 50

# Applying the Kalman Filter
for i in range(0, N_iter):
    (X, P) = kf_predict(X, P, A, Q, B, U)
    (X, P, K, IM, IS, LH)  = kf_update(X, P, Y, H, R)
    Y = np.array([[X[0,0] + abs(0.1 * np.random.randn(1)[0])], [X[1, 0] + abs(0.1 * np.random.randn(1)[0])]])
    print (Y)#queria ver o output

[[0.29352787]
 [0.14480904]]
[[0.41033768]
 [0.21025101]]
[[0.55322827]
 [0.25708717]]
[[0.54241808]
 [0.46685546]]
[[0.58425079]
 [0.45610939]]
[[0.59928269]
 [0.44363717]]
[[0.72985379]
 [0.69250525]]
[[0.80636425]
 [0.61415357]]
[[0.78280744]
 [0.65110366]]
[[0.88491687]
 [0.76153462]]
[[0.92003193]
 [0.80992209]]
[[1.09462646]
 [0.81431075]]
[[1.15173013]
 [0.85928864]]
[[1.21231196]
 [0.95260814]]
[[1.22000404]
 [0.92966687]]
[[1.23079374]
 [0.99836745]]
[[1.25293962]
 [1.00296652]]
[[1.31867668]
 [1.02018134]]
[[1.486787  ]
 [1.15201715]]
[[1.47851059]
 [1.31525956]]
[[1.48253832]
 [1.26894974]]
[[1.50950422]
 [1.36915762]]
[[1.52414518]
 [1.37515411]]
[[1.55766477]
 [1.41674959]]
[[1.62395056]
 [1.49762869]]
[[1.68571065]
 [1.62110159]]
[[1.70307463]
 [1.59745231]]
[[1.72705314]
 [1.66016049]]
[[1.76140823]
 [1.76531154]]
[[1.80238566]
 [1.76495395]]
[[1.97693607]
 [1.87421515]]
[[1.96358098]
 [1.85851221]]
[[2.0825898]
 [1.9475094]]
[[2.12197857]
 [1.9874535 ]]
[[2.17150846]
 [

In [11]:
A.T


array([[1. , 0. , 0. , 0. ],
       [0. , 1. , 0. , 0. ],
       [0.1, 0. , 1. , 0. ],
       [0. , 0.1, 0. , 1. ]])

In [12]:
A

array([[1. , 0. , 0.1, 0. ],
       [0. , 1. , 0. , 0.1],
       [0. , 0. , 1. , 0. ],
       [0. , 0. , 0. , 1. ]])